### ISSUE TITLE
"Basic World" test failing in master

### ISSUE THREAD

**Issue by joel-petersen** [shakiba/planck.js#24]
My results are:
  10 passing (58ms)
  1 failing

  1) Basic World:
     Error: expected 0.0025000000000000005 to be near 0
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.expect.Assertion.near (test/testutil/expect.js:35:8)
      at Context.<anonymous> (test/BasicTest.js:43:17)

There is also a missing dependency on the Mocha test framework.

PS- This looks like great port of box2d to javascript, congrats.

**Comment by s-iaroshenko** [comment]
Fixed in PR 124

**Comment by shakiba** [comment]
Thanks @s-iaroshenko !
